### ISSUE TITLE
HTMLText breaks in Jetpack Compose preview on Android Studio Electric Eel

### ISSUE THREAD

**Issue by Abhiek187** [Abhiek187/ez-recipes-android#24]
Ever since I updated to Electric Eel, I'm unable to preview the `HTMLText` composable. The preview code in the main branch worked in Dolphin, so this seems to be a bug with Electric Eel. I've added the full stack trace below.

> at com.abhiek.ezrecipes.utils.HTMLTextKt$HTMLText$2$1.invoke(HTMLText.kt:44)

The line in question is:

```kotlin
view.text = HtmlCompat.fromHtml(html, HtmlCompat.FROM_HTML_MODE_COMPACT)
```

And the code block that triggers the null pointer exception can be found in [Android's source code](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/text/Html.java;l=869?q=html&ss=android%2Fplatform%2Fsuperproject):

```java
if (tag.equalsIgnoreCase("b")) {
    Application application = ActivityThread.currentApplication();
    int fontWeightAdjustment = application.getResources().getConfiguration().fontWeightAdjustment;
    end(mSpannableStringBuilder, Bold.class, new StyleSpan(Typeface.BOLD, fontWeightAdjustment));
}
```

The code breaks if the HTML string contains a `<b>` or `<strong>` tag. This issue is currently being tracked at https://issuetracker.google.com/issues/262773698.

```
java.lang.NullPointerException
	at android.text.HtmlToSpannedConverter.handleEndTag(Html.java:869)
	at android.text.HtmlToSpannedConverter.endElement(Html.java:1247)
	at org.ccil.cowan.tagsoup.Parser.pop(Parser.java:737)
	at org.ccil.cowan.tagsoup.Parser.etag_basic(Parser.java:707)
	at org.ccil.cowan.tagsoup.Parser.etag(Parser.java:645)
	at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:552)
	at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:450)
	at android.text.HtmlToSpannedConverter.convert(Html.java:751)
	at android.text.Html.fromHtml(Html.java:246)
	at android.text.Html.fromHtml(Html.java:200)
	at androidx.core.text.HtmlCompat$Api24Impl.fromHtml(HtmlCompat.java:194)
	at androidx.core.text.HtmlCompat.fromHtml(HtmlCompat.java:150)
	at com.abhiek.ezrecipes.utils.HTMLTextKt$HTMLText$2$1.invoke(HTMLText.kt:44)
	at com.abhiek.ezrecipes.utils.HTMLTextKt$HTMLText$2$1.invoke(HTMLText.kt:43)
	at androidx.compose.ui.viewinterop.ViewFactoryHolder$updateBlock$1.invoke(AndroidView.android.kt:186)
	at androidx.compose.ui.viewinterop.ViewFactoryHolder$updateBlock$1.invoke(AndroidView.android.kt:186)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2139)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:130)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:126)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:126)
	at androidx.compose.ui.viewinterop.AndroidViewHolder$runUpdate$1.invoke(AndroidViewHolder.android.kt:170)
	at androidx.compose.ui.viewinterop.AndroidViewHolder$runUpdate$1.invoke(AndroidViewHolder.android.kt:168)
	at androidx.compose.ui.viewinterop.AndroidViewHolder.setUpdate(AndroidViewHolder.android.kt:108)
	at androidx.compose.ui.viewinterop.ViewFactoryHolder.setUpdateBlock(AndroidView.android.kt:186)
	at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$2$5.invoke(AndroidView.android.kt:130)
	at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$2$5.invoke(AndroidView.android.kt:130)
	at androidx.compose.runtime.ComposerImpl$apply$operation$1.invoke(Composer.kt:1621)
	at androidx.compose.runtime.ComposerImpl$apply$operation$1.invoke(Composer.kt:1619)
	at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(Composer.kt:3450)
	at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(Composer.kt:3447)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:808)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:839)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:978)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1060)
	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:182)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:202)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1147)
	at android.view.View.dispatchAttachedToWindow(View.java:21291)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:58)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:367)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:443)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:722)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:879)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:194)
	at com.android.tools.idea.rendering.RenderExecutor$PriorityRunnable.run(RenderExecutor.kt:292)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Abhiek187** [comment]
I can confirm that removing the `<b>` tags fixed the issue. Funny how this is the 2nd time I have encountered a newly-found bug while working on this project. The first time was in [ez-recipes-server #47](https://github.com/Abhiek187/ez-recipes-server/issues/47) when an Axios update broke the server. But unlike then, it's not as convenient for me to roll back to Dolphin until the issue is patched.

**Comment by Abhiek187** [comment]
Fixed in Studio Giraffe Canary 2.
The fix will also be backported to Studio Flamingo Beta 2.
